server:
  port: 8080
spring:
  application:
    name: pizzas
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true